obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[-0.15,-0.15],[-0.15,0.15],[0.15,0.15],[0.15,-0.15]]
# footprint_padding: 0.02
transform_tolerance: 0.8

inflation_radius: 1.0
cost_scaling_factor: 3.0

map_type: costmap

observation_sources: laser_scan_sensor #point_cloud_sensor
laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}


# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
