# static_map - True if using existing map

global_costmap:
  global_frame: map
  robot_base_frame: base_footprint

  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: true
  # resolution: 0.04
  # width: 5.0
  # height: 5.0
  # cost_scaling_factor: 10.0

  # obstacle_layer:
  #   enabled: false
  
